export const ISSUE_DESCRIPTIONS: Record<string, string> = {
  sharia_jurisdiction: 'Secular governance (-5) to full Sharia implementation (+5)',
  fiscal_autonomy: 'Strong centralism (-5) to confederalism (+5)',
  chinese_relations: 'Western pivot (-5) to deepen WAFTA/China ties (+5)',
  bic_reform: 'Abolish BIC (-5) to preserve BIC (+5)',
  ethnic_quotas: 'Pure meritocracy (-5) to strong affirmative action (+5)',
  fertility_policy: 'Population control (-5) to pro-natalism (+5)',
  constitutional_structure: 'Parliamentary system (-5) to presidential (+5)',
  resource_revenue: 'Federal monopoly (-5) to local control (+5)',
  housing: 'Pure market housing (-5) to state intervention (+5)',
  education: 'Radical localism (-5) to meritocratic centralism (+5)',
  labor_automation: 'Pro-capital/automation (-5) to pro-labor protection (+5)',
  military_role: 'Full civilian control (-5) to military guardianship (+5)',
  immigration: 'Open borders (-5) to restrictionism (+5)',
  language_policy: 'Vernacular languages (-5) to English supremacy (+5)',
  womens_rights: 'Traditional patriarchy (-5) to aggressive feminism (+5)',
  traditional_authority: 'Marginalization (-5) to formal integration (+5)',
  infrastructure: 'Targeted provision (-5) to universal provision (+5)',
  land_tenure: 'Customary land rights (-5) to formalization (+5)',
  taxation: 'Low tax/small state (-5) to high redistribution (+5)',
  agricultural_policy: 'Free market agriculture (-5) to protectionist smallholder (+5)',
  biological_enhancement: 'Prohibition (-5) to universal access (+5)',
  trade_policy: 'Autarky (-5) to full trade openness (+5)',
  environmental_regulation: 'Growth first (-5) to strong regulation (+5)',
  media_freedom: 'State media control (-5) to full press freedom (+5)',
  healthcare: 'Pure market healthcare (-5) to universal provision (+5)',
  pada_status: 'Anti-Pada (-5) to Pada preservation (+5)',
  energy_policy: 'Fossil status quo (-5) to green transition (+5)',
  az_restructuring: 'Return to 36+ states (-5) to keep 8 AZs (+5)',
};
